### ISSUE TITLE
Storyline context

### ISSUE THREAD

**Issue by PJY00** [PJY00/escape-school#2]
스토리랑 관련 텍스트 짜야되는데 스토리 상세하게 짜주실 분 구합니다.
엔딩도 여러 개 넣어야 하나 고민인데 어떻게 할까요?

**Comment by euune** [comment]
스토리텔링

처음 강의실 화면이 나오고 검은 화면으로 전환(잠듦)
어?? 나 잠들었었나.. 몇시야.. 8시?? 빨리 나가야겠다
덜컹덜컹(잠겨있음)
어떡하지
NPC 다가가기
저기.. 여기 문 닫혔는데.. 혹시 여기 문 열 수 있으세요..?
NPC: 저도 비밀번호 다는 모르는데 한 자리만 알고 있어요.. 게임을 통과하시면 한 자리 알려드릴게요.
게임중
비밀번호 한 자리 얻음
엘레베이터 탐
?? 왜 안 내려가지
조건 발견
간단한 수학 문제를 푸시면 한 층 내려갑니다..?
수학문제 풀기
반복*4
드디어 일층이다
문 열기
띠링
드디어 나왔다 벌써 아침이네 지금 몇시지 7시...
나 오늘 몇교시야.. 에타확인
1교시네 망할
THE END 
끝! 수업시간에 잠들기 말자


이런식으로 하면 어때요?

**Comment by minjungE** [comment]
좋아욤

2024년 12월 3일 (화) 오후 8:09, unne-source ***@***.***>님이 작성:

**Comment by euune** [comment]
추가적인 아이디어 있을까요?

**Comment by wlsd9** [comment]
성공 엔딩이랑 실패 엔딩 두가지만 하나요?

**Comment by PJY00** [comment]
아마 그렇지 않을까요? 뭐 더 해도 괜찮긴 해요

**Comment by eunchaeseo05** [comment]
힌트 이제 정해서 나눠야 할거 같아요. 각자의 게임 다 맞추고 힌트 제공될 때 나오는 숫자는 각자 알아서 정해서 할까요?
